name: Release & Deploy

on:
  workflow_dispatch:
    inputs:
      save-draft:
        description: 'Save draft'
        required: false
        default: false
        type: boolean
      release-tag-suffix:
        description: 'Release tag suffix'
        required: false
      release-notes:
        description: 'Release notes'
      release-pre:
        description: 'Prerelease'
        required: false
        default: false
        type: boolean
      append-generated-notes:
        description: 'Append generated notes'
        required: false
        default: false
        type: boolean
jobs:
  release-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies
      run: npm ci

    - name: Build project
      run: npm run build

    - name: Extract package version
      id: package-version
      run: |
        VERSION=$(jq -r .version package.json)
        echo "version=${VERSION}" >> $GITHUB_OUTPUT

    - name: Create Release
      uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda
      with:
        draft: ${{ github.event.inputs.save-draft }}
        body: ${{ github.event.inputs.release-notes }}
        prerelease: ${{ github.event.inputs.release-pre }}
        tag_name: v${{ steps.package-version.outputs.version }}${{ github.event.inputs.release-tag-suffix }}
        generate_release_notes: ${{ github.event.inputs.append-generated-notes }}
        fail_on_unmatched_files: true
        files: |
          dist/test1.html
          readme.md

    - name: Rename to index.html
      run: mv dist/test1.html dist/index.html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
